# load("@prelude//toolchains:demo.bzl", "system_demo_toolchains")


# All the default toolchains, suitable for a quick demo or early prototyping.
# Most real projects should copy/paste the implementation to configure them.
# system_demo_toolchains()

load("@prelude//toolchains:go.bzl", "system_go_toolchain")
load("@prelude//toolchains:python.bzl", "system_python_bootstrap_toolchain")
load("//:go_cc.bzl", "cc_go_toolchain")

system_python_bootstrap_toolchain(
    name = "python_bootstrap",
    visibility = ["PUBLIC"],
)

system_go_toolchain(
    name = "go",
    visibility = ["PUBLIC"],
)

cc_go_toolchain(
    name = "go_linux",
    visibility = ["PUBLIC"],
    go_arch = "amd64",
    go_os = "linux",
)
