# load("@prelude//toolchains:demo.bzl", "system_demo_toolchains")


# All the default toolchains, suitable for a quick demo or early prototyping.
# Most real projects should copy/paste the implementation to configure them.
# system_demo_toolchains()

load("@prelude//toolchains:go.bzl", "system_go_toolchain")
load("@prelude//toolchains:python.bzl", "system_python_bootstrap_toolchain")
load("//:go_cc.bzl", "cc_go_toolchain")

system_python_bootstrap_toolchain(
    name = "python_bootstrap",
    visibility = ["PUBLIC"],
)

cc_go_toolchain(
    name = "go",
    visibility = ["PUBLIC"],
    go_arch = select({
        "config//cpu:x86_64": "amd64",
        "config//cpu:arm64": "arm64",
    }),
    go_os = select({
        "config//os:linux": "linux",
        "config//os:macos": "darwin",
    }),
)
